Resolved the merge conflict
modakanalytics/bigquery.almaren pull request #5
Opened 2022-02-08 12:49 UTC by chintanpallik1999

@mantovani @badrinathpatchikolla  please review.

2022-02-08 13:54 UTC, mantovani requested changes
Let's also upgrade almaren for the latest version.

2022-02-08 14:19 UTC, kishor3107 commented
@mantovani  Updated.

2022-02-11 13:41 UTC, badrinathpatchikolla approved these changes

2022-02-11 13:41 UTC, badrinathpatchikolla commented on build.sbt
> +  "com.github.music-of-the-ainur" %% "almaren-framework" % "2.4.5-2.4.5" % "provided",
This is not the latest version of Almaren

2022-02-14 07:04 UTC, badrinathpatchikolla approved these changes

2022-02-14 07:05 UTC, badrinathpatchikolla commented
@mantovani  Please review and release 0.0.3 version for BigQuery Almaren

2022-02-14 14:56 UTC, mantovani approved these changes

2022-02-14 14:56 UTC, merged